
services:
  - type: web
    name: quizgenius-api
    env: python
    region: oregon
    plan: free

    buildCommand: pip install -r requirements.txt && python migrate_db.py

    startCommand: >
      uvicorn main:app
      --host 0.0.0.0
      --port $PORT
      --timeout-keep-alive 120
      --timeout-graceful-shutdown 30
      --log-level info

    healthCheckPath: /ping

    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "15"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
